git-debimport lxc_1.0.5.orig.tar.xz

diff --git a/templates/lxc-busybox.in b/templates/lxc-busybox.in
--- a/templates/lxc-busybox.in
+++ b/templates/lxc-busybox.in
@@ -18,7 +18,31 @@
 
 # You should have received a copy of the GNU Lesser General Public
 # License along with this library; if not, write to the Free Software
-# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
+
+# Detect use under userns (unsupported)
+for arg in "$@"; do
+    [ "$arg" = "--" ] && break
+    if [ "$arg" = "--mapped-uid" -o "$arg" = "--mapped-gid" ]; then
+        echo "This template can't be used for unprivileged containers." 1>&2
+        echo "You may want to try the \"download\" template instead." 1>&2
+        exit 1
+    fi
+done
+
+# Make sure the usual locations are in PATH
+export PATH=$PATH:/usr/sbin:/usr/bin:/sbin:/bin
+
+am_in_userns() {
+    [ -e /proc/self/uid_map ] || { echo no; return; }
+    [ "$(wc -l /proc/self/uid_map | awk '{ print $1 }')" -eq 1 ] || { echo yes; return; }
+    line=$(awk '{ print $1 " " $2 " " $3 }' /proc/self/uid_map)
+    [ "$line" = "0 0 4294967295" ] && { echo no; return; }
+    echo yes
+}
+
+in_userns=0
+[ $(am_in_userns) = "yes" ] && in_userns=1
 
 install_busybox()
 {
@@ -33,8 +57,11 @@ $rootfs/root \
 $rootfs/etc \
 $rootfs/etc/init.d \
 $rootfs/bin \
+$rootfs/usr/bin \
 $rootfs/sbin \
+$rootfs/usr/sbin \
 $rootfs/proc \
+$rootfs/sys \
 $rootfs/mnt \
 $rootfs/tmp \
 $rootfs/var/log \
@@ -52,17 +79,22 @@ $rootfs/usr/lib64"
     pushd $rootfs/dev > /dev/null || return 1
 
     # minimal devices needed for busybox
-    mknod tty c 5 0       || res=1
-    mknod console c 5 1   || res=1
-    chmod 666 tty console || res=1
-    mknod tty0 c 4 0      || res=1
-    mknod tty1 c 4 0      || res=1
-    mknod tty5 c 4 0      || res=1
-    chmod 666 tty0        || res=1
-    mknod ram0 b 1 0      || res=1
-    chmod 600 ram0        || res=1
-    mknod null c 1 3      || res=1
-    chmod 666 null        || res=1
+    if [ $in_userns -eq 1 ]; then
+        for dev in tty console tty0 tty1 tty5 ram0 null urandom; do
+            touch $rootfs/dev/$dev
+            echo "/dev/$dev dev/$dev    none bind 0 0" >> $path/fstab
+        done
+    else
+        mknod -m 666 tty c 5 0       || res=1
+        mknod -m 666 console c 5 1   || res=1
+        mknod -m 666 tty0 c 4 0      || res=1
+        mknod -m 666 tty1 c 4 0      || res=1
+        mknod -m 666 tty5 c 4 0      || res=1
+        mknod -m 600 ram0 b 1 0      || res=1
+        mknod -m 666 null c 1 3      || res=1
+        mknod -m 666 zero c 1 5      || res=1
+        mknod -m 666 urandom c 1 9   || res=1
+    fi
 
     popd > /dev/null
 
@@ -88,7 +120,6 @@ EOF
 
     # mount points
     cat <<EOF >> $rootfs/etc/fstab
-proc  /proc      proc    defaults     0      0
 shm   /dev/shm   tmpfs   defaults     0      0
 EOF
 
@@ -108,36 +139,34 @@ EOF
 
     cat <<EOF >> $rootfs/usr/share/udhcpc/default.script
 #!/bin/sh
-
 case "\$1" in
-	deconfig)
-		ip addr flush dev \$interface
-                ;;
+    deconfig)
+        ip addr flush dev \$interface
+        ;;
 
-	renew|bound)
+    renew|bound)
+        # flush all the routes
+        if [ -n "\$router" ]; then
+            ip route del default 2> /dev/null
+        fi
 
-                # flush all the routes
-		if [ -n "\$router" ]; then
-                        ip route del default 2> /dev/null
-		fi
+        # check broadcast
+        if [ -n "\$broadcast" ]; then
+            broadcast="broadcast \$broadcast"
+        fi
 
-                # check broadcast
-                if [ -n "\$broadcast" ]; then
-                        broadcast="broadcast \$broadcast"
-                fi
+        # add a new ip address
+        ip addr add \$ip/\$mask \$broadcast dev \$interface
 
-                # add a new ip address
-		ip addr add \$ip/\$mask \$broadcast dev \$interface
+        if [ -n "\$router" ]; then
+            ip route add default via \$router dev \$interface
+        fi
 
-		if [ -n "\$router" ]; then
-                        ip route add default via \$router dev \$interface
-                fi
-
-		[ -n "\$domain" ] && echo search \$domain > /etc/resolv.conf
-		for i in \$dns ; do
-			echo nameserver \$i >> /etc/resolv.conf
-		done
-		;;
+        [ -n "\$domain" ] && echo search \$domain > /etc/resolv.conf
+        for i in \$dns ; do
+            echo nameserver \$i >> /etc/resolv.conf
+        done
+        ;;
 esac
 exit 0
 EOF
@@ -151,63 +180,35 @@ configure_busybox()
 {
     rootfs=$1
 
-    functions="\
-	[ [[ addgroup adduser adjtimex ar arp arping ash awk basename \
-	brctl bunzip2 bzcat bzip2 cal cat catv chattr chgrp chmod \
-	chown chpasswd chpst chroot chrt chvt cksum clear cmp comm \
-	cp cpio crond crontab cryptpw cut date dc dd deallocvt \
-	delgroup deluser df dhcprelay diff dirname dmesg dnsd dos2unix \
-	du dumpkmap dumpleases echo ed egrep eject env envdir envuidgid \
-	ether-wake expand expr fakeidentd false fbset fdformat fdisk \
-	fetchmail fgrep find findfs fold free freeramdisk fsck \
-	fsck.minix ftpget ftpput fuser getopt getty grep gunzip gzip \
-	halt hdparm head hexdump hostid hostname httpd hwclock id \
-	ifconfig ifdown ifenslave ifup inetd init insmod install ip \
-	ipaddr ipcalc ipcrm ipcs iplink iproute iprule iptunnel \
-	kbd_mode kill killall killall5 klogd last length less linux32 \
-	linux64 linuxrc ln loadfont loadkmap logger login logname \
-	logread losetup lpd lpq lpr ls lsattr lsmod lzmacat makedevs \
-	md5sum mdev mesg microcom mkdir mkfifo mkfs.minix mknod mkswap \
-	mktemp modprobe more mount mountpoint msh mt mv nameif nc \
-	netstat nice nmeter nohup nslookup od openvt passwd patch \
-	pgrep pidof ping ping6 pipe_progress pivot_root pkill poweroff \
-	printenv printf ps pscan pwd raidautorun rdate readahead \
-	readlink readprofile realpath reboot renice reset resize rm \
-	rmdir rmmod route rpm rpm2cpio run-parts runlevel runsv \
-	runsvdir rx script sed sendmail seq setarch setconsole \
-	setkeycodes setlogcons setsid setuidgid sh sha1sum slattach \
-	sleep softlimit sort split start-stop-daemon stat strings \
-	stty su sulogin sum sv svlogd swapoff swapon switch_root \
-	sync sysctl syslogd tac tail tar taskset tcpsvd tee telnet \
-	telnetd test tftp tftpd time top touch tr traceroute \
-	true tty ttysize udhcpc udhcpd udpsvd umount uname uncompress \
-	unexpand uniq unix2dos unlzma unzip uptime usleep uudecode \
-	uuencode vconfig vi vlock watch watchdog wc wget which \
-	who whoami xargs yes zcat zcip"
-
-    type busybox >/dev/null
+    which busybox >/dev/null 2>&1
 
     if [ $? -ne 0 ]; then
-	echo "busybox executable is not accessible"
-	return 1
+        echo "busybox executable is not accessible"
+        return 1
     fi
 
-    file $(which busybox) | grep -q "statically linked"
+    file -L $(which busybox) | grep -q "statically linked"
     if [ $? -ne 0 ]; then
-	echo "warning : busybox is not statically linked."
-	echo "warning : The template script may not correctly"
-	echo "warning : setup the container environment."
+        echo "warning : busybox is not statically linked."
+        echo "warning : The template script may not correctly"
+        echo "warning : setup the container environment."
     fi
 
     # copy busybox in the rootfs
     cp $(which busybox) $rootfs/bin
     if [ $? -ne 0 ]; then
-	echo "failed to copy busybox in the rootfs"
-	return 1
+        echo "failed to copy busybox in the rootfs"
+        return 1
     fi
 
-    # do hardlink to busybox for the different commands
-    for i in $functions; do ln $rootfs/bin/busybox $rootfs/bin/$i; done
+    # symlink busybox for the commands it supports
+    # it would be nice to just use "chroot $rootfs busybox --install -s /bin"
+    # but that only works right in a chroot with busybox >= 1.19.0
+    pushd $rootfs/bin > /dev/null || return 1
+    ./busybox --help | grep 'Currently defined functions:' -A300 | \
+      grep -v 'Currently defined functions:' | tr , '\n' | \
+      xargs -n1 ln -s busybox
+    popd > /dev/null
 
     # relink /sbin/init
     ln $rootfs/bin/busybox $rootfs/sbin/init
@@ -215,9 +216,63 @@ configure_busybox()
     # passwd exec must be setuid
     chmod +s $rootfs/bin/passwd
     touch $rootfs/etc/shadow
-    chroot $rootfs /bin/passwd -d root
 
-    echo "No password for 'root', please change !"
+    # setting passwd for root
+    CHPASSWD_FILE=$rootfs/root/chpasswd.sh
+
+    cat <<EOF >$CHPASSWD_FILE
+echo "setting root password to \"root\""
+
+mount -n --bind /lib $rootfs/lib
+if [ \$? -ne 0 ]; then
+    echo "Failed bind-mounting /lib at $rootfs/lib"
+    exit 1
+fi
+
+chroot $rootfs chpasswd <<EOFF 2>/dev/null
+root:root
+EOFF
+
+
+if [ \$? -ne 0 ]; then
+    echo "Failed to change root password"
+    exit 1
+fi
+
+umount $rootfs/lib
+
+EOF
+
+    lxc-unshare -s MOUNT -- /bin/sh < $CHPASSWD_FILE
+    rm $CHPASSWD_FILE
+
+    # add ssh functionality if dropbear package available on host
+    which dropbear >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        # copy dropbear binary
+        cp $(which dropbear) $rootfs/usr/sbin
+        if [ $? -ne 0 ]; then
+            echo "Failed to copy dropbear in the rootfs"
+            return 1
+        fi
+
+        # make symlinks to various ssh utilities
+        utils="\
+            $rootfs/usr/bin/dbclient \
+            $rootfs/usr/bin/scp \
+            $rootfs/usr/bin/ssh \
+            $rootfs/usr/sbin/dropbearkey \
+            $rootfs/usr/sbin/dropbearconvert \
+        "
+        echo $utils | xargs -n1 ln -s /usr/sbin/dropbear
+
+        # add necessary config files
+        mkdir $rootfs/etc/dropbear
+        dropbearkey -t rsa -f $rootfs/etc/dropbear/dropbear_rsa_host_key > /dev/null 2>&1
+        dropbearkey -t dss -f $rootfs/etc/dropbear/dropbear_dss_host_key > /dev/null 2>&1
+
+        echo "'dropbear' ssh utility installed"
+    fi
 
     return 0
 }
@@ -228,26 +283,31 @@ copy_configuration()
     rootfs=$2
     name=$3
 
+grep -q "^lxc.rootfs" $path/config 2>/dev/null || echo "lxc.rootfs = $rootfs" >> $path/config
 cat <<EOF >> $path/config
+lxc.haltsignal = SIGUSR1
 lxc.utsname = $name
 lxc.tty = 1
 lxc.pts = 1
-lxc.rootfs = $rootfs
+lxc.cap.drop = sys_module mac_admin mac_override sys_time
+
+# When using LXC with apparmor, uncomment the next line to run unconfined:
+#lxc.aa_profile = unconfined
 EOF
 
-if [ -d "$rootfs/lib" ]; then
-cat <<EOF >> $path/config
-lxc.mount.entry=/lib $rootfs/lib none ro,bind 0 0
-lxc.mount.entry=/usr/lib $rootfs/usr/lib none ro,bind 0 0
-EOF
-fi
+    libdirs="\
+        lib \
+        usr/lib \
+        lib64 \
+        usr/lib64"
 
-if [ -d "/lib64" ] && [ -d "$rootfs/lib64" ]; then
-cat <<EOF >> $path/config
-lxc.mount.entry=/lib64 $rootfs/lib64 none ro,bind 0 0
-lxc.mount.entry=/usr/lib64 $rootfs/usr/lib64 none ro,bind 0 0
-EOF
-fi
+    for dir in $libdirs; do
+        if [ -d "/$dir" ] && [ -d "$rootfs/$dir" ]; then
+            echo "lxc.mount.entry = /$dir $dir none ro,bind 0 0" >> $path/config
+        fi
+    done
+    echo "lxc.mount.entry = /sys/kernel/security sys/kernel/security none ro,bind,optional 0 0" >>$path/config
+    echo "lxc.mount.auto = proc:mixed sys" >>$path/config
 }
 
 usage()
@@ -258,10 +318,10 @@ EOF
     return 0
 }
 
-options=$(getopt -o hp:n: -l help,path:,name: -- "$@")
+options=$(getopt -o hp:n: -l help,rootfs:,path:,name: -- "$@")
 if [ $? -ne 0 ]; then
-        usage $(basename $0)
-	exit 1
+    usage $(basename $0)
+    exit 1
 fi
 eval set -- "$options"
 
@@ -270,7 +330,8 @@ do
     case "$1" in
         -h|--help)      usage $0 && exit 0;;
         -p|--path)      path=$2; shift 2;;
-	-n|--name)      name=$2; shift 2;;
+        --rootfs)       rootfs=$2; shift 2;;
+        -n|--name)      name=$2; shift 2;;
         --)             shift 1; break ;;
         *)              break ;;
     esac
@@ -286,7 +347,15 @@ if [ -z "$path" ]; then
     exit 1
 fi
 
-rootfs=$path/rootfs
+# detect rootfs
+config="$path/config"
+if [ -z "$rootfs" ]; then
+    if grep -q '^lxc.rootfs' $config 2>/dev/null ; then
+        rootfs=$(awk -F= '/^lxc.rootfs =/{ print $2 }' $config)
+    else
+        rootfs=$path/rootfs
+    fi
+fi
 
 install_busybox $rootfs $name
 if [ $? -ne 0 ]; then
